//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHUNGTU
    {
        public System.Guid KHOA { get; set; }
        public string SCT { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string SCT2 { get; set; }
        public Nullable<System.DateTime> NGAY2 { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public string MADVI2 { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public Nullable<int> DELETED_BY { get; set; }
    }
}
