//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHOMHH
    {
        public int IDNHOM { get; set; }
        public string TENNHOM { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public string GHICHU { get; set; }
    }
}
