//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TONKHO
    {
        public System.Guid KHOA { get; set; }
        public Nullable<int> NAMKY { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> KY { get; set; }
        public string MADVI { get; set; }
        public Nullable<int> LG_DAU { get; set; }
        public Nullable<int> LG_NHAP { get; set; }
        public Nullable<int> LG_XUAT { get; set; }
        public Nullable<int> LG_CUOI { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    }
}
