//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FUNC_SYS_RIGHT
    {
        public string FUNC_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> ISGROUP { get; set; }
        public string PARENT { get; set; }
        public Nullable<int> SORT { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public string Không { get; set; }
    }
}
