USE [QUANLY_KHOHANG]
GO

/****** Object:  Table [dbo].[tb_CHUNGTU_CT]    Script Date: 12/25/2024 4:21:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_CHUNGTU_CT](
	[KHOACT] [uniqueidentifier] NOT NULL,
	[KHOA] [uniqueidentifier] NULL,
	[NGAY] [datetime] NULL,
	[SOLUONG] [int] NULL,
	[DONGIA] [float] NULL,
	[THANHTIEN] [float] NULL,
 CONSTRAINT [PK_tb_CHUNGTU_CT] PRIMARY KEY CLUSTERED 
(
	[KHOACT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


