USE [QUANLY_KHOHANG]
GO

/****** Object:  Table [dbo].[tb_DVT]    Script Date: 12/25/2024 4:22:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_DVT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEN] [nvarchar](200) NULL,
 CONSTRAINT [PK_tb_DVT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


