USE [QUANLY_KHOHANG]
GO

/****** Object:  Table [dbo].[tb_DONVI]    Script Date: 12/25/2024 4:22:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_DONVI](
	[MADVI] [nvarchar](10) NOT NULL,
	[TENDVI] [nvarchar](200) NULL,
	[DIENTHOAI] [nvarchar](20) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[FAX] [nvarchar](20) NULL,
	[DIACHI] [nvarchar](500) NULL,
	[DISABLED] [bit] NULL,
	[KHO] [bit] NULL,
	[MACTY] [nvarchar](10) NOT NULL,
	[KYHIEU] [nvarchar](10) NULL,
 CONSTRAINT [PK_tb_DONVI] PRIMARY KEY CLUSTERED 
(
	[MADVI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


