USE [QUANLY_KHOHANG]
GO

/****** Object:  Table [dbo].[tb_HANGHOA]    Script Date: 12/25/2024 4:23:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_HANGHOA](
	[BARCODE] [nvarchar](13) NOT NULL,
	[TENHH] [nvarchar](50) NULL,
	[TENTAT] [nvarchar](50) NULL,
	[DVT] [nvarchar](50) NULL,
	[DONGIA] [float] NULL,
	[MANCC] [int] NULL,
	[MAXX] [int] NULL,
	[IDNHOM] [int] NULL,
	[MOTA] [nvarchar](500) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [int] NULL,
	[DISABLED] [bit] NULL,
 CONSTRAINT [PK_tb_HANGHOA] PRIMARY KEY CLUSTERED 
(
	[BARCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


