USE [QUANLY_KHOHANG]
GO

/****** Object:  Table [dbo].[tb_NHACUNGCAP]    Script Date: 12/25/2024 4:23:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_NHACUNGCAP](
	[MANCC] [int] IDENTITY(1,1) NOT NULL,
	[TENNCC] [nvarchar](200) NULL,
	[DIENTHOAI] [nvarchar](20) NULL,
	[FAX] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[DIACHI] [nvarchar](500) NULL,
	[CREATE_DATE] [datetime] NULL,
	[DISABLED] [bit] NULL,
 CONSTRAINT [PK_tb_NHACUNGCAP] PRIMARY KEY CLUSTERED 
(
	[MANCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


