USE [QUANLY_KHOHANG]
GO

/****** Object:  Table [dbo].[tb_SYS_FUNC]    Script Date: 12/25/2024 4:24:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_SYS_FUNC](
	[FUNC_CODE] [varchar](50) NOT NULL,
	[SORT] [int] NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[ISGROUP] [bit] NULL,
	[PARENT] [varchar](50) NULL,
	[MENU] [bit] NULL,
	[TIPS] [nvarchar](max) NULL,
 CONSTRAINT [PK_tb_SYS_FUNC] PRIMARY KEY CLUSTERED 
(
	[FUNC_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


