USE QUANLY_KHOHANG
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tb_SYS_REPORT]') AND type in (N'U'))
DROP TABLE [dbo].[tb_SYS_REPORT]
GO

USE QUANLY_KHOHANG
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tb_SYS_REPORT](
	[REP_CODE] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](50) NULL,
	[REP_NAME] [nvarchar](50) NULL,
	[VISIBLE] [bit] NULL,
	[TUNGAY] [bit] NULL,
	[THANGNAM] [bit] NULL,
	[MACTY] [bit] NULL,
	[MADVI] [bit] NULL,
    CONSTRAINT [PK_tb_SYS_REPORT] PRIMARY KEY CLUSTERED ([REP_CODE] ASC)
)

GO