USE QUANLY_KHOHANG
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tb_SYS_RIGHT_REP]') AND type in (N'U'))
DROP TABLE [dbo].[tb_SYS_RIGHT_REP]
GO

USE QUANLY_KHOHANG
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tb_SYS_RIGHT_REP](
	[REP_CODE] [nvarchar](50) NOT NULL,
	[IDUSER] [int] NULL,
	[USER_RIGHT] [int] NULL,
    CONSTRAINT [PK_tb_SYS_RIGHT_REP] PRIMARY KEY CLUSTERED ([REP_CODE] ASC)
)

GO