USE QUANLY_KHOHANG
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tb_SYS_RIGHT]') AND type in (N'U'))
DROP TABLE [dbo].[tb_SYS_RIGHT]
GO

USE QUANLY_KHOHANG
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tb_SYS_RIGHT](
	[FUNC_CODE] [nvarchar](50) NOT NULL,
	[IDUSER] [int] NULL,
	[USER_RIGHT] [int] NULL,
    CONSTRAINT [PK_tb_SYS_RIGHT] PRIMARY KEY CLUSTERED ([FUNC_CODE] ASC)
)

GO