USE [QUANLY_KHOHANG]
GO

/****** Object:  Table [dbo].[tb_TONKHO]    Script Date: 10/15/2024 6:48:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_TONKHO](
	[KHOA] [uniqueidentifier] NOT NULL,
	[NAMKY] [int] NULL,
	[NAM] [int] NULL,
	[KY] [int] NULL,
	[MADVI] [nvarchar](50) NULL,
	[LG_DAU] [int] NULL,
	[LG_NHAP] [int] NULL,
	[LG_XUAT] [int] NULL,
	[LG_CUOI] [int] NULL,
	[THANHTIEN] [float] NULL,
	[NGAY] [datetime] NULL,
 CONSTRAINT [PK_tb_TONKHO] PRIMARY KEY CLUSTERED 
(
	[KHOA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


